const FACEBOOK_APP_ID = "";
const GOOGLE_IOS_ID = "";
const GOOGLE_ANDROID_ID =
	""; //DEV
const GOOGLE_ANDROID_ID_STANDALONE =
	""; //PROD
const API_URL = "http://5e08ac18434a370014168b98.mockapi.io/api/v1"; //FUTURE IMPLEMENTATION

export {
	FACEBOOK_APP_ID,
	GOOGLE_IOS_ID,
	GOOGLE_ANDROID_ID,
	GOOGLE_ANDROID_ID_STANDALONE,
	API_URL,
}
